### PR TITLE
Update BTPrimaryGeneratorAction.cpp

### PR DESCRIPTION
**Pull request by Dhruv581**
Added Second Particle Gun for Neutrons

---
This change is [Reviewable](https://reviewable.io/reviews/waterloo-rocketry/payload-sims/9)

### CODE REVIEW

**Review by PCModeActivate — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/payload-sims/9)* status: all files reviewed, 1 unresolved discussion (waiting on @DanielShteinbok, @Dhruv581, @dldyment, @jacobdeery, @kylemtam, and @SaduniSumith)

*[a discussion](https://reviewable.io/reviews/waterloo-rocketry/payload-sims/9#-MNRJmYx80_91xJWbsfK:-MNRJmYy9wGdSBEiGxD-:bscrzci) (no related file):*
By the looks of it, the only changes in this PR consist of adding a new particle gun. As far as I am aware, the additional parameter does not conflict with any unchanged files, so if the data are correct, it looks good to me.

---

**Review by kylemtam — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/payload-sims/9)* status: all files reviewed, 5 unresolved discussions (waiting on @DanielShteinbok, @Dhruv581, @dldyment, @jacobdeery, and @SaduniSumith)

___
*[BTPrimaryGeneratorAction.cpp, line 31 at r1](https://reviewable.io/reviews/waterloo-rocketry/payload-sims/9#-MNRj0Vw4zylHeLU44sQ:-MNRj0Vw4zylHeLU44sR:b-kol6el) ([raw file](https://github.com/waterloo-rocketry/payload-sims/blob/a5ca730b215639a3aa80944d3dbedf82f5387dcc/BTPrimaryGeneratorAction.cpp#L31)):*
> ```cpp
>         = particleTable->FindParticle(particleName = "gamma");
>     fParticleGun->SetParticleDefinition(particle);
>     fParticleGun->SetParticleMomentumDirection(G4ThreeVector(0., 0., 1.));
> ```

I realize this is the default value, but do you know what the units are and is this realistic for this to go in the positive z-direction? (if you change this to -1, you need to correct line 78 as well)
___
*[BTPrimaryGeneratorAction.cpp, line 43 at r1](https://reviewable.io/reviews/waterloo-rocketry/payload-sims/9#-MNRh7vm1jisVBexWmkP:-MNRh7vm1jisVBexWmkQ:b2ds16v) ([raw file](https://github.com/waterloo-rocketry/payload-sims/blob/a5ca730b215639a3aa80944d3dbedf82f5387dcc/BTPrimaryGeneratorAction.cpp#L43)):*
> ```cpp
>     nParticleGun->SetParticleDefinition(particle);
>     nParticleGun->SetParticleMomentumDirection(G4ThreeVector(0., 0., 1.));
>     nParticleGun->SetParticleEnergy(1. * MeV);
> ```

why is this 1 MeV while the other is 10 MeV? Was this intentional?
___
*[BTPrimaryGeneratorAction.cpp, line 77 at r1](https://reviewable.io/reviews/waterloo-rocketry/payload-sims/9#-MNRkdXpE9IOpGHg7SNf:-MNRkdXpE9IOpGHg7SNg:b-xytexj) ([raw file](https://github.com/waterloo-rocketry/payload-sims/blob/a5ca730b215639a3aa80944d3dbedf82f5387dcc/BTPrimaryGeneratorAction.cpp#L77)):*
> ```cpp
> 
>     const G4double x0 = size * envSizeXY * (G4UniformRand() - 0.5);
>     const G4double yo = size * envSizeXY * (G4UniformRand() - 0.5);
> ```

Do you know how x0 and y0 are calculated?
___
*[BTPrimaryGeneratorAction.cpp, line 78 at r1](https://reviewable.io/reviews/waterloo-rocketry/payload-sims/9#-MNRkW5F0Ept8Wh9ebEw:-MNRkW5F0Ept8Wh9ebEx:blbe157) ([raw file](https://github.com/waterloo-rocketry/payload-sims/blob/a5ca730b215639a3aa80944d3dbedf82f5387dcc/BTPrimaryGeneratorAction.cpp#L78)):*
> ```cpp
>     const G4double x0 = size * envSizeXY * (G4UniformRand() - 0.5);
>     const G4double yo = size * envSizeXY * (G4UniformRand() - 0.5);
>     const G4double z0 = -0.5 * envSizeZ;
> ```

See comment on line 31: suggested change -0.5->0.5

**Review by Dhruv581 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/payload-sims/9)* status: all files reviewed, 5 unresolved discussions (waiting on @DanielShteinbok, @Dhruv581, @dldyment, @jacobdeery, @kylemtam, @PCModeActivate, and @SaduniSumith)

*[a discussion](https://reviewable.io/reviews/waterloo-rocketry/payload-sims/9#-MNRJmYx80_91xJWbsfK:-MNWePBSCmWDy2wpLMcN:b-896fix) (no related file):*
<details><summary><i>Previously, PCModeActivate (Robert Cai) wrote…</i></summary><blockquote>

By the looks of it, the only changes in this PR consist of adding a new particle gun. As far as I am aware, the additional parameter does not conflict with any unchanged files, so if the data are correct, it looks good to me.
</blockquote></details>

Done.

---
___
*[BTPrimaryGeneratorAction.cpp, line 43 at r1](https://reviewable.io/reviews/waterloo-rocketry/payload-sims/9#-MNRh7vm1jisVBexWmkP:-MNWea-87I_kOuv2FCtE:bsp5wy3) ([raw file](https://github.com/waterloo-rocketry/payload-sims/blob/a5ca730b215639a3aa80944d3dbedf82f5387dcc/BTPrimaryGeneratorAction.cpp#L43)):*
<details><summary><i>Previously, kylemtam (Kyle Tam) wrote…</i></summary><blockquote>

why is this 1 MeV while the other is 10 MeV? Was this intentional?
</blockquote></details>

This was intentional.
___
*[BTPrimaryGeneratorAction.cpp, line 77 at r1](https://reviewable.io/reviews/waterloo-rocketry/payload-sims/9#-MNRkdXpE9IOpGHg7SNf:-MNWgobH4qLUOKLIpYBC:bn1q4jl) ([raw file](https://github.com/waterloo-rocketry/payload-sims/blob/a5ca730b215639a3aa80944d3dbedf82f5387dcc/BTPrimaryGeneratorAction.cpp#L77)):*
<details><summary><i>Previously, kylemtam (Kyle Tam) wrote…</i></summary><blockquote>

Do you know how x0 and y0 are calculated?
</blockquote></details>

Do not know, I left this as Default from the B1 example.

**Review by kylemtam — APPROVED** [review]
I'm good with the stuff on the research side of things. Just awaiting approval from Robert et al.

> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/payload-sims/9#-:-MNWjaCI7hUNXukM3XMa:byjcujn)* status: all files reviewed, 4 unresolved discussions (waiting on @DanielShteinbok, @Dhruv581, @dldyment, @jacobdeery, @kylemtam, @PCModeActivate, and @SaduniSumith)

**Review by PCModeActivate — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/payload-sims/9)* status: all files reviewed, 3 unresolved discussions (waiting on @DanielShteinbok, @Dhruv581, @dldyment, @jacobdeery, @kylemtam, and @SaduniSumith)

___
*[BTPrimaryGeneratorAction.cpp, line 31 at r1](https://reviewable.io/reviews/waterloo-rocketry/payload-sims/9#-MNRj0Vw4zylHeLU44sQ:-MNZ3jaMDM6u57WbCLcv:b-g99ah2) ([raw file](https://github.com/waterloo-rocketry/payload-sims/blob/a5ca730b215639a3aa80944d3dbedf82f5387dcc/BTPrimaryGeneratorAction.cpp#L31)):*
<details><summary><i>Previously, kylemtam (Kyle Tam) wrote…</i></summary><blockquote>

I realize this is the default value, but do you know what the units are and is this realistic for this to go in the positive z-direction? (if you change this to -1, you need to correct line 78 as well)
</blockquote></details>

This may need to be changed; I'm not sure if the momentum is constant for every particle, but in a beam example, it appears that the predef momentum is set to be -1 if its shooting from top to bottom.
___
*[BTPrimaryGeneratorAction.cpp, line 77 at r1](https://reviewable.io/reviews/waterloo-rocketry/payload-sims/9#-MNRkdXpE9IOpGHg7SNf:-MNZ3TLg6NM29AW6oUlI:b-6rxhuu) ([raw file](https://github.com/waterloo-rocketry/payload-sims/blob/a5ca730b215639a3aa80944d3dbedf82f5387dcc/BTPrimaryGeneratorAction.cpp#L77)):*
<details><summary><i>Previously, Dhruv581 wrote…</i></summary><blockquote>

Do not know, I left this as Default from the B1 example.
</blockquote></details>

Not sure what `size` is, but if I'm not mistaken this should randomly scatter particles in the environment dimensions.
___
*[BTPrimaryGeneratorAction.cpp, line 78 at r1](https://reviewable.io/reviews/waterloo-rocketry/payload-sims/9#-MNRkW5F0Ept8Wh9ebEw:-MNZ2yPf9MYQRCQ4l55P:bq4y8hh) ([raw file](https://github.com/waterloo-rocketry/payload-sims/blob/a5ca730b215639a3aa80944d3dbedf82f5387dcc/BTPrimaryGeneratorAction.cpp#L78)):*
<details><summary><i>Previously, kylemtam (Kyle Tam) wrote…</i></summary><blockquote>

See comment on line 31: suggested change -0.5->0.5
</blockquote></details>

While x0,y0 being random should not be a problem, I believe if we are modeling particles shooting from the top of the box to the bottom then it should be changed to 0.5 or 1 here.

**Review by kylemtam — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/payload-sims/9#-:-MNaqq4o2J2wghHsF3_a:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @DanielShteinbok, @dldyment, @jacobdeery, and @SaduniSumith)

___
*[BTPrimaryGeneratorAction.cpp, line 31 at r1](https://reviewable.io/reviews/waterloo-rocketry/payload-sims/9#-MNRj0Vw4zylHeLU44sQ:-MNaqUJe7QSWp4pK-oPQ:b-kxi4ja) ([raw file](https://github.com/waterloo-rocketry/payload-sims/blob/a5ca730b215639a3aa80944d3dbedf82f5387dcc/BTPrimaryGeneratorAction.cpp#L31)):*
<details><summary><i>Previously, PCModeActivate (Robert Cai) wrote…</i></summary><blockquote>

This may need to be changed; I'm not sure if the momentum is constant for every particle, but in a beam example, it appears that the predef momentum is set to be -1 if its shooting from top to bottom.
</blockquote></details>

@pcmodeactivate do you think you could share a link to the beam example in #payload?

**Pull request merged**
