### PR TITLE
Added build test run manager

### PR DESCRIPTION
**Pull request by dldyment**
the run manager brings all of the other files (detector construction, action generator, etc) together into one program, i.e. it assembles the application from it's components

---
This change is [Reviewable](https://reviewable.io/reviews/waterloo-rocketry/payload-sims/2)

### CODE REVIEW

**Review by kylemtam — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/payload-sims/2)* status: all files reviewed, 1 unresolved discussion (waiting on @dldyment, @jacobdeery, @pauladam316, and @SaduniSumith)

*[a discussion](https://reviewable.io/reviews/waterloo-rocketry/payload-sims/2#-MHijwbr1tCR8GHej6nm:-MHijwbsEVM-ieASyFmE:b-ega9dx) (no related file):*
I see nothing concerning at first glance. Maybe Jacob will catch some semantic stuff but :lgtm1: :lgtm2:

---

**Review by jacobdeery — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/payload-sims/2)* status: all files reviewed, 6 unresolved discussions (waiting on @dldyment, @pauladam316, and @SaduniSumith)

___
*[BuildTest.cpp, line 4 at r1](https://reviewable.io/reviews/waterloo-rocketry/payload-sims/2#-MHkxy31D86rM75TXXuO:-MHkxy31D86rM75TXXuP:bugocfx) ([raw file](https://github.com/waterloo-rocketry/payload-sims/blob/4d03b162597fe64225c117f73c99df692497d72a/BuildTest.cpp#L4)):*
> ```
> #ifdef G4MULTITHREADED
> ```
I assume this was taken from an example. Do we actually need support for running both multithreaded and singlethreaded, or can we just use one of them?
___
*[BuildTest.cpp, line 16 at r1](https://reviewable.io/reviews/waterloo-rocketry/payload-sims/2#-MHkz0hV9KKJOPRAz8LV:-MHkz0hV9KKJOPRAz8LW:b-57cx4o) ([raw file](https://github.com/waterloo-rocketry/payload-sims/blob/4d03b162597fe64225c117f73c99df692497d72a/BuildTest.cpp#L16)):*
> ```cpp
> #include "G4UIExecutive.hh"
> 
> #include "Randomize.hh"
> ```

We don't use anything from this header, do we? I don't think it needs to be included
___
*[BuildTest.cpp, line 20 at r1](https://reviewable.io/reviews/waterloo-rocketry/payload-sims/2#-MHkyQta3XbLHXztT-PJ:-MHkyQta3XbLHXztT-PK:b-b3ytpf) ([raw file](https://github.com/waterloo-rocketry/payload-sims/blob/4d03b162597fe64225c117f73c99df692497d72a/BuildTest.cpp#L20)):*
> ```
> ///detect interactive mode and define UI session
> ```
Nit: please write comments like this: `// two slashes, then a space, then the text`
___
*[BuildTest.cpp, line 20 at r1](https://reviewable.io/reviews/waterloo-rocketry/payload-sims/2#-MHky_Q5AdlQNAXmYmLf:-MHky_Q5AdlQNAXmYmLg:b55v0gg) ([raw file](https://github.com/waterloo-rocketry/payload-sims/blob/4d03b162597fe64225c117f73c99df692497d72a/BuildTest.cpp#L20)):*
> ```cpp
> int main(int argc, char** argv)
> {
> 	///detect interactive mode and define UI session
> ```

Nit: mixing tabs and spaces in this file, please choose one or the other
___
*[BuildTest.cpp, line 21 at r1](https://reviewable.io/reviews/waterloo-rocketry/payload-sims/2#-MHky7ex1Kuh8RwCZMfV:-MHky7ex1Kuh8RwCZMfW:b-sx6m74) ([raw file](https://github.com/waterloo-rocketry/payload-sims/blob/4d03b162597fe64225c117f73c99df692497d72a/BuildTest.cpp#L21)):*
> ```
> 0
> ```
`nullptr`

**Review by dldyment — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/payload-sims/2)* status: all files reviewed, 4 unresolved discussions (waiting on @dldyment, @jacobdeery, @pauladam316, and @SaduniSumith)

___
*[BuildTest.cpp, line 4 at r1](https://reviewable.io/reviews/waterloo-rocketry/payload-sims/2#-MHkxy31D86rM75TXXuO:-MI2V6hb40D8-Mv7mPjG:b-r7zt5u) ([raw file](https://github.com/waterloo-rocketry/payload-sims/blob/4d03b162597fe64225c117f73c99df692497d72a/BuildTest.cpp#L4)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

> ```
> #ifdef G4MULTITHREADED
> ```
I assume this was taken from an example. Do we actually need support for running both multithreaded and singlethreaded, or can we just use one of them?
</blockquote></details>

we can just use one here, I removed it.
___
*[BuildTest.cpp, line 16 at r1](https://reviewable.io/reviews/waterloo-rocketry/payload-sims/2#-MHkz0hV9KKJOPRAz8LV:-MI2VFgJ2pB-acs9UPu-:b-jop3kq) ([raw file](https://github.com/waterloo-rocketry/payload-sims/blob/4d03b162597fe64225c117f73c99df692497d72a/BuildTest.cpp#L16)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

We don't use anything from this header, do we? I don't think it needs to be included
</blockquote></details>

oh whoops, good catch. there was a part in the example I based this off of that needed it, but we didn't. I forgot to remove that header
___
*[BuildTest.cpp, line 20 at r1](https://reviewable.io/reviews/waterloo-rocketry/payload-sims/2#-MHkyQta3XbLHXztT-PJ:-MI2VY2D-_TMHjdPKbCO:bb7f2mf) ([raw file](https://github.com/waterloo-rocketry/payload-sims/blob/4d03b162597fe64225c117f73c99df692497d72a/BuildTest.cpp#L20)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

> ```
> ///detect interactive mode and define UI session
> ```
Nit: please write comments like this: `// two slashes, then a space, then the text`
</blockquote></details>

done
___
*[BuildTest.cpp, line 20 at r1](https://reviewable.io/reviews/waterloo-rocketry/payload-sims/2#-MHky_Q5AdlQNAXmYmLf:-MI2VYmL-GLvFsw_6jlF:bb7f2mf) ([raw file](https://github.com/waterloo-rocketry/payload-sims/blob/4d03b162597fe64225c117f73c99df692497d72a/BuildTest.cpp#L20)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

Nit: mixing tabs and spaces in this file, please choose one or the other
</blockquote></details>

done
___
*[BuildTest.cpp, line 21 at r1](https://reviewable.io/reviews/waterloo-rocketry/payload-sims/2#-MHky7ex1Kuh8RwCZMfV:-MI2VZVQCDsWXicH7Gh3:bb7f2mf) ([raw file](https://github.com/waterloo-rocketry/payload-sims/blob/4d03b162597fe64225c117f73c99df692497d72a/BuildTest.cpp#L21)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

> ```
> 0
> ```
`nullptr`
</blockquote></details>

done

**Review by jacobdeery — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/payload-sims/2)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @dldyment, @kylemtam, @pauladam316, and @SaduniSumith)

*[a discussion](https://reviewable.io/reviews/waterloo-rocketry/payload-sims/2#-MHijwbr1tCR8GHej6nm:-MJYqdrJ7oDjbhepfHkf:bls5b6i) (no related file):*
<details><summary><i>Previously, kylemtam (Kyle Tam) wrote…</i></summary><blockquote>

I see nothing concerning at first glance. Maybe Jacob will catch some semantic stuff but :lgtm1: :lgtm2:
</blockquote></details>

Approving with minor comments, feel free to merge once addressed (no re-review required)

---
___
*[BuildTest.cpp, line 16 at r1](https://reviewable.io/reviews/waterloo-rocketry/payload-sims/2#-MHkz0hV9KKJOPRAz8LV:-MJYqXKe42rm5qkrhKgj:b70yhag) ([raw file](https://github.com/waterloo-rocketry/payload-sims/blob/4d03b162597fe64225c117f73c99df692497d72a/BuildTest.cpp#L16)):*
<details><summary><i>Previously, dldyment (Delaney Dyment) wrote…</i></summary><blockquote>

oh whoops, good catch. there was a part in the example I based this off of that needed it, but we didn't. I forgot to remove that header
</blockquote></details>

Still needs to be removed
___
*[BuildTest.cpp, line 20 at r1](https://reviewable.io/reviews/waterloo-rocketry/payload-sims/2#-MHky_Q5AdlQNAXmYmLf:-MJYqPIn4QCXL5m8h-GQ:buwjqcy) ([raw file](https://github.com/waterloo-rocketry/payload-sims/blob/4d03b162597fe64225c117f73c99df692497d72a/BuildTest.cpp#L20)):*
<details><summary><i>Previously, dldyment (Delaney Dyment) wrote…</i></summary><blockquote>

done
</blockquote></details>

Doesn't seem to be done, but not a blocker here

**Pull request merged**
