### PR TITLE
Update BTPrimaryGeneratorAction.hh

### PR DESCRIPTION
**Pull request by Dhruv581**
Added Second Particle Gun

---
This change is [Reviewable](https://reviewable.io/reviews/waterloo-rocketry/payload-sims/8)

### CODE REVIEW

**Review by jacobdeery — COMMENTED** [review]
It looks like this PR is necessary for #9 to work properly. Is there a reason this change isn't just part of PR #9?

**Review by jacobdeery — APPROVED** [review]
Oh, I see, this is a PR against `PhysicsGun`, not against `master`. That's fine, but usually for such a small change you would be ok to just push it directly to `PhysicsGun`

**Comment by Dhruv581** [comment]
Sorry about that I think I accidentally created a new branch when committing, still learning how to use Git.

**Comment by PCModeActivate** [comment]
Yeah, this doesn't need to be in a new branch

**Review by PCModeActivate — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/payload-sims/8)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @DanielShteinbok, @dldyment, @kylemtam, and @SaduniSumith)

**Pull request merged**
