### PR TITLE
Event action

### PR DESCRIPTION
**Pull request by PCModeActivate**
Includes only an empty event action file & header that does not contain any functions other than the constructor/destructor etc that allows an event to be ran as it is passed in.

---
This change is [Reviewable](https://reviewable.io/reviews/waterloo-rocketry/payload-sims/5)

### CODE REVIEW

**Comment by kylemtam** [comment]
I assume that someone wants this PR reviewed as no reviewers were assigned. I've self-assigned myself and Jacob but please tell me I'm wrong if I am Robert/Delaney

**Review by kylemtam — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/payload-sims/5)* status: 0 of 2 files reviewed, 7 unresolved discussions (waiting on @chrissank, @jacobdeery, @kylemtam, and @PCModeActivate)

*[a discussion](https://reviewable.io/reviews/waterloo-rocketry/payload-sims/5#-MJiqSra-oVL0XuLLHHy:-MJiqSra-oVL0XuLLHHz:b-n6evj) (no related file):*
Some minor changes requested. Looking good though!

---
___
*[include/BTEventAction.hh, line 24 at r4](https://reviewable.io/reviews/waterloo-rocketry/payload-sims/5#-MJimABi4CiCJtMVuG1N:-MJimABi4CiCJtMVuG1O:btoh0s9) ([raw file](https://github.com/waterloo-rocketry/payload-sims/blob/4a1e1c3302fdf9c4917101c3302e8bb6f05029b6/include/BTEventAction.hh#L24)):*
> ```Hack
> // * use  in  resulting  scientific  publications,  and indicate your *
> // * acceptance of all terms of the Geant4 Software license.          *
> // ********************************************************************
> ```

Re: license stuff, I believe usually a separate license file is defined to stipulate all the nitty-gritty stuff on the repo. Might be worth making that and putting all of the above there instead of here?
___
*[include/BTEventAction.hh, line 31 at r4](https://reviewable.io/reviews/waterloo-rocketry/payload-sims/5#-MJiot3qEVM7KL_illE7:-MJiot3qEVM7KL_illE8:bxv01fs) ([raw file](https://github.com/waterloo-rocketry/payload-sims/blob/4a1e1c3302fdf9c4917101c3302e8bb6f05029b6/include/BTEventAction.hh#L31)):*
> ```
> #ifndef BTEventAction_h
> #define BTEventAction_h 1
> ```
I think you can use `#pragma once` instead of header guards here
___
*[include/BTEventAction.hh, line 38 at r4](https://reviewable.io/reviews/waterloo-rocketry/payload-sims/5#-MJinvs415YwDopQHM6W:-MJinvs415YwDopQHM6X:bvf7ced) ([raw file](https://github.com/waterloo-rocketry/payload-sims/blob/4a1e1c3302fdf9c4917101c3302e8bb6f05029b6/include/BTEventAction.hh#L38)):*
> ```Hack
> class BTRunAction;
> 
> /// Event action class
> ```

Jacob Nit: please write comments like this: `// two slashes, then a space, then the text`
___
*[include/BTEventAction.hh, line 39 at r4](https://reviewable.io/reviews/waterloo-rocketry/payload-sims/5#-MJipHYk4HQKMVr6nyF7:-MJipHYk4HQKMVr6nyF8:b9p29b6) ([raw file](https://github.com/waterloo-rocketry/payload-sims/blob/4a1e1c3302fdf9c4917101c3302e8bb6f05029b6/include/BTEventAction.hh#L39)):*
> ```Hack
> 
> /// Event action class
> ///
> ```

Empty comment? Plz delete if not used
___
*[include/BTEventAction.hh, line 57 at r4](https://reviewable.io/reviews/waterloo-rocketry/payload-sims/5#-MJinqHnA_bpoeQSLIuf:-MJinqHnA_bpoeQSLIug:b-9097h3) ([raw file](https://github.com/waterloo-rocketry/payload-sims/blob/4a1e1c3302fdf9c4917101c3302e8bb6f05029b6/include/BTEventAction.hh#L57)):*
> ```Hack
> };
> 
> //....oooOO0OOooo........oooOO0OOooo........oooOO0OOooo........oooOO0OOooo......
> ```

Delete this. It's too spooky for October
___
*[src/BTEventAction.cc, line 24 at r4](https://reviewable.io/reviews/waterloo-rocketry/payload-sims/5#-MJipal-DCdY46CQVcYP:-MJipal-DCdY46CQVcYQ:b3gbrsk) ([raw file](https://github.com/waterloo-rocketry/payload-sims/blob/4a1e1c3302fdf9c4917101c3302e8bb6f05029b6/src/BTEventAction.cc#L24)):*
> ```cpp
> // * use  in  resulting  scientific  publications,  and indicate your *
> // * acceptance of all terms of the Geant4 Software license.          *
> // ********************************************************************
> ```

See comment on licensing in previous file and then potentially delete
___
*[src/BTEventAction.cc, line 36 at r4](https://reviewable.io/reviews/waterloo-rocketry/payload-sims/5#-MJipeMr7cCiEyNg2_RD:-MJipeMr7cCiEyNg2_RE:bx6ygpq) ([raw file](https://github.com/waterloo-rocketry/payload-sims/blob/4a1e1c3302fdf9c4917101c3302e8bb6f05029b6/src/BTEventAction.cc#L36)):*
> ```cpp
> #include "G4RunManager.hh"
> 
> //....oooOO0OOooo........oooOO0OOooo........oooOO0OOooo........oooOO0OOooo......
> ```

Delete the spooky stuff

**Review by jacobdeery — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/payload-sims/5)* status: 0 of 2 files reviewed, 7 unresolved discussions (waiting on @chrissank, @jacobdeery, @kylemtam, and @PCModeActivate)

___
*[include/BTEventAction.hh, line 24 at r4](https://reviewable.io/reviews/waterloo-rocketry/payload-sims/5#-MJimABi4CiCJtMVuG1N:-MJm7OkO07U0CiClow1u:brytlqw) ([raw file](https://github.com/waterloo-rocketry/payload-sims/blob/4a1e1c3302fdf9c4917101c3302e8bb6f05029b6/include/BTEventAction.hh#L24)):*
<details><summary><i>Previously, kylemtam (Kyle Tam) wrote…</i></summary><blockquote>

Re: license stuff, I believe usually a separate license file is defined to stipulate all the nitty-gritty stuff on the repo. Might be worth making that and putting all of the above there instead of here?
</blockquote></details>

It looks like this file was pretty much directly copied from a GEANT4 example, including the license header. We can delete this.

**Review by PCModeActivate — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/payload-sims/5)* status: 0 of 2 files reviewed, 7 unresolved discussions (waiting on @chrissank, @kylemtam, and @PCModeActivate)

___
*[include/BTEventAction.hh, line 31 at r4](https://reviewable.io/reviews/waterloo-rocketry/payload-sims/5#-MJiot3qEVM7KL_illE7:-MK7J4LgAoTtXEQgTFMk:bb7j2lb) ([raw file](https://github.com/waterloo-rocketry/payload-sims/blob/4a1e1c3302fdf9c4917101c3302e8bb6f05029b6/include/BTEventAction.hh#L31)):*
<details><summary><i>Previously, kylemtam (Kyle Tam) wrote…</i></summary><blockquote>

> ```
> #ifndef BTEventAction_h
> #define BTEventAction_h 1
> ```
I think you can use `#pragma once` instead of header guards here
</blockquote></details>

What exactly is the difference here between #pragma once and header guard? Why/When do we prefer one over another?

**Review by PCModeActivate — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/payload-sims/5)* status: 0 of 2 files reviewed, 7 unresolved discussions (waiting on @chrissank, @kylemtam, and @PCModeActivate)

___
*[include/BTEventAction.hh, line 24 at r4](https://reviewable.io/reviews/waterloo-rocketry/payload-sims/5#-MJimABi4CiCJtMVuG1N:-MK7K3kr5zEvdzF-4bGX:b-896fix) ([raw file](https://github.com/waterloo-rocketry/payload-sims/blob/4a1e1c3302fdf9c4917101c3302e8bb6f05029b6/include/BTEventAction.hh#L24)):*
<details><summary><i>Previously, jacobdeery (Jacob Deery) wrote…</i></summary><blockquote>

It looks like this file was pretty much directly copied from a GEANT4 example, including the license header. We can delete this.
</blockquote></details>

Done.
___
*[include/BTEventAction.hh, line 31 at r4](https://reviewable.io/reviews/waterloo-rocketry/payload-sims/5#-MJiot3qEVM7KL_illE7:-MK7K5C5Dj4s4I3KtY2M:b-896fix) ([raw file](https://github.com/waterloo-rocketry/payload-sims/blob/4a1e1c3302fdf9c4917101c3302e8bb6f05029b6/include/BTEventAction.hh#L31)):*
<details><summary><i>Previously, PCModeActivate (Robert Cai) wrote…</i></summary><blockquote>

What exactly is the difference here between #pragma once and header guard? Why/When do we prefer one over another?
</blockquote></details>

Done.
___
*[include/BTEventAction.hh, line 39 at r4](https://reviewable.io/reviews/waterloo-rocketry/payload-sims/5#-MJipHYk4HQKMVr6nyF7:-MK7KCU6CRCOOeDj9AxO:b-896fix) ([raw file](https://github.com/waterloo-rocketry/payload-sims/blob/4a1e1c3302fdf9c4917101c3302e8bb6f05029b6/include/BTEventAction.hh#L39)):*
<details><summary><i>Previously, kylemtam (Kyle Tam) wrote…</i></summary><blockquote>

Empty comment? Plz delete if not used
</blockquote></details>

Done.
___
*[include/BTEventAction.hh, line 57 at r4](https://reviewable.io/reviews/waterloo-rocketry/payload-sims/5#-MJinqHnA_bpoeQSLIuf:-MK7KEFu4uh9mm82u0e1:b-896fix) ([raw file](https://github.com/waterloo-rocketry/payload-sims/blob/4a1e1c3302fdf9c4917101c3302e8bb6f05029b6/include/BTEventAction.hh#L57)):*
<details><summary><i>Previously, kylemtam (Kyle Tam) wrote…</i></summary><blockquote>

Delete this. It's too spooky for October
</blockquote></details>

Done.
___
*[src/BTEventAction.cc, line 24 at r4](https://reviewable.io/reviews/waterloo-rocketry/payload-sims/5#-MJipal-DCdY46CQVcYP:-MK7KFBl3i2rLC19VxLB:b-896fix) ([raw file](https://github.com/waterloo-rocketry/payload-sims/blob/4a1e1c3302fdf9c4917101c3302e8bb6f05029b6/src/BTEventAction.cc#L24)):*
<details><summary><i>Previously, kylemtam (Kyle Tam) wrote…</i></summary><blockquote>

See comment on licensing in previous file and then potentially delete
</blockquote></details>

Done.
___
*[src/BTEventAction.cc, line 36 at r4](https://reviewable.io/reviews/waterloo-rocketry/payload-sims/5#-MJipeMr7cCiEyNg2_RD:-MK7KFpK2LLeWsjPIZez:b-896fix) ([raw file](https://github.com/waterloo-rocketry/payload-sims/blob/4a1e1c3302fdf9c4917101c3302e8bb6f05029b6/src/BTEventAction.cc#L36)):*
<details><summary><i>Previously, kylemtam (Kyle Tam) wrote…</i></summary><blockquote>

Delete the spooky stuff
</blockquote></details>

Done.

**Review by PCModeActivate — COMMENTED** [review]
> Reviewed 1 of 2 files at r5, 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/payload-sims/5)* status: all files reviewed, 7 unresolved discussions (waiting on @kylemtam)

*[a discussion](https://reviewable.io/reviews/waterloo-rocketry/payload-sims/5#-MJiqSra-oVL0XuLLHHy:-MKBwyy5BG2_c4nEgNy2:b-896fix) (no related file):*
<details><summary><i>Previously, kylemtam (Kyle Tam) wrote…</i></summary><blockquote>

Some minor changes requested. Looking good though!
</blockquote></details>

Done.

---

**Review by kylemtam — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/payload-sims/5)* status: all files reviewed, 1 unresolved discussion (waiting on @PCModeActivate)

___
*[include/BTEventAction.hh, line 31 at r4](https://reviewable.io/reviews/waterloo-rocketry/payload-sims/5#-MJiot3qEVM7KL_illE7:-MKCUjth4mtEIgnfwumK:bk3ddwn) ([raw file](https://github.com/waterloo-rocketry/payload-sims/blob/4a1e1c3302fdf9c4917101c3302e8bb6f05029b6/include/BTEventAction.hh#L31)):*
>In the C and C++ programming languages, #pragma once is a non-standard but widely supported preprocessor directive designed to cause the current source file to be included only once in a single compilation. Thus, #pragma once serves the same purpose as #include guards, but with several advantages, including: less code, avoiding name clashes, and improved compile speed.
___
*[include/BTEventAction.hh, line 39 at r4](https://reviewable.io/reviews/waterloo-rocketry/payload-sims/5#-MJipHYk4HQKMVr6nyF7:-MKCVHxo45f0laZ0QSSX:b-jr0gfi) ([raw file](https://github.com/waterloo-rocketry/payload-sims/blob/4a1e1c3302fdf9c4917101c3302e8bb6f05029b6/include/BTEventAction.hh#L39)):*
<details><summary><i>Previously, PCModeActivate (Robert Cai) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I think it's still there?

**Review by kylemtam — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/payload-sims/5)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[include/BTEventAction.hh, line 39 at r4](https://reviewable.io/reviews/waterloo-rocketry/payload-sims/5#-MJipHYk4HQKMVr6nyF7:-MKCVsZYDiSHech-x4_D:b-9zc45k) ([raw file](https://github.com/waterloo-rocketry/payload-sims/blob/4a1e1c3302fdf9c4917101c3302e8bb6f05029b6/include/BTEventAction.hh#L39)):*
<details><summary><i>Previously, kylemtam (Kyle Tam) wrote…</i></summary><blockquote>

I think it's still there?
</blockquote></details>

This isn't worth blocking. Once this is removed, consider this approved

**Pull request merged**
